<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-26 01:17

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('templavoila');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_templavoila_cm1' => $extensionPath . 'cm1/index.php',
	'tx_templavoila_staticds_check' => $extensionClassesPath . 'staticds/class.tx_templavoila_staticds_check.php',
	'tx_templavoila_staticds_wizard' => $extensionClassesPath . 'staticds/class.tx_templavoila_staticds_wizard.php',
	'tx_templavoila_cm1_ajax' => $extensionPath . 'cm1/class.tx_templavoila_cm1_ajax.php',
	'tx_templavoila_cm1_dsedit' => $extensionPath . 'cm1/class.tx_templavoila_cm1_dsedit.php',
	'tx_templavoila_cm1_etypes' => $extensionPath . 'cm1/class.tx_templavoila_cm1_etypes.php',
	'tx_templavoila_cm2' => $extensionPath . 'cm2/index.php',
	'tx_templavoila_mod1_ajax' => $extensionPath . 'mod1/class.tx_templavoila_mod1_ajax.php',
	'tx_templavoila_mod1_clipboard' => $extensionPath . 'mod1/class.tx_templavoila_mod1_clipboard.php',
	'tx_templavoila_mod1_localization' => $extensionPath . 'mod1/class.tx_templavoila_mod1_localization.php',
	'tx_templavoila_mod1_recordlist' => $extensionPath . 'mod1/class.tx_templavoila_mod1_recordlist.php',
	'tx_templavoila_mod1_records' => $extensionPath . 'mod1/class.tx_templavoila_mod1_records.php',
	'tx_templavoila_mod1_sidebar' => $extensionPath . 'mod1/class.tx_templavoila_mod1_sidebar.php',
	'tx_templavoila_mod1_specialdoktypes' => $extensionPath . 'mod1/class.tx_templavoila_mod1_specialdoktypes.php',
	'tx_templavoila_mod1_wizards' => $extensionPath . 'mod1/class.tx_templavoila_mod1_wizards.php',
	'tx_templavoila_dbnewcontentel' => $extensionPath . 'mod1/db_new_content_el.php',
	'tx_templavoila_module1' => $extensionPath . 'mod1/index.php',
	'tx_templavoila_module2' => $extensionPath . 'mod2/index.php',
	'tx_templavoila_pi1' => $extensionPath . 'pi1/class.tx_templavoila_pi1.php',
);
