<?php
/**
 * Language labels for module "web_txtemplavoilaM1"
 *
 * $Id$
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		'title' => "WEB > PAGE MODULE",
		'default_introduction' => 'If you wish to edit the content of a page, please click the page title in the page tree to the left.',
		'createnewpage_title' => 'Create a new page',
		'createnewpage_introduction' => '',
		'createnewpage_hide_header' => 'Hide',
		'createnewpage_hide_description' => 'Hide the created page from the public',
		'createnewpage_pagetitle_header' => 'Page title',
		'createnewpage_pagetitle_description' => 'Entering a page title is required and helps you to identify your page later.',
		'createnewpage_templateobject_header' => 'Layout',
		'createnewpage_templateobject_description' => 'In order to create a page please click on one of the layouts below or press the default layout button.',
		'createnewpage_defaultlayoutsubmitlabel' => 'Create page with default layout',
		'createnewpage_templateobject_createemptypage' => 'Create an empty page based on this template:',
		'createnewpage_templateobject_createpagewithdefaultcontent' => 'Create a page with default content based on this template:',
		'createnewcontent_newContentElement' => 'New content element',
		'template_nodescriptionavailable' => 'No description available.',
		'template_titledefault' => 'Default template',
		'template_descriptiondefault' => 'Default layout, defined by this website\'s designer.',
		'newce_defaulttext_text' => 'Please enter some text here',
		'view_basic' => 'Basic view',
		'view_tree' => 'Tree view',
		'view_fancy' => 'Special fancy view',
		'ruleapplies' => 'Rule applies',
		'rulefails' => 'Does not comply with the rules',
		'createnewrecord' => 'Create new record',
		'editrecord' => 'Edit record',
		'pasterecord' => 'Paste record',
		'copyrecord' => 'Copy record',
		'cutrecord' => 'Cut record',
		'createreference' => 'Create reference',
		'unlinkRecord' => 'Unlink record',
		'deleteRecord' => 'Delete record (!)',
		'deleteRecordMsg' => 'Do you really want to delete this record?',
		'hideheaderinformation' => 'Hide page related information',
		'showheaderinformation' => 'Show page related information',
		'makeLocal' => 'Create local copy',
		'makeLocalMsg' => 'Do you want to create a local copy of this referenced element?',
		'path' => 'Path',
	),
	"dk" => Array (
		'title' => "Web > Side module",
		'default_introduction' => 'Hvis du ønsker at redigere sidens indhold, så klik på sidetitlen i sidetræet til venstre.',
		'createnewpage_title' => 'Opret ny side',
		'createnewpage_introduction' => '',
		'createnewpage_hide_header' => 'Skjul',
		'createnewpage_hide_description' => 'Skjul den oprettede side fra offentligheden',
		'createnewpage_pagetitle_header' => 'Side titel',
		'createnewpage_pagetitle_description' => 'Det er nødvendigt at angive en sidetitel som også vil hjælpe dig med at identificere siden senere.',
		'createnewpage_templateobject_header' => 'Layout',
		'createnewpage_templateobject_description' => 'For at oprette en side så klik på et at billederne herunder eller knappen for standardlayoutet.',
		'createnewpage_defaultlayoutsubmitlabel' => 'Opret side med standardlayout',
		'createnewpage_templateobject_createemptypage' => 'Opret en tom side baseret på denne skabelon:',
		'createnewpage_templateobject_createpagewithdefaultcontent' => 'Opret en side med standard indhold baseret på denne skabelon:',
		'createnewcontent_newContentElement' => 'Nyt indholdselement',
		'template_nodescriptionavailable' => 'Ingen beskrivelse tilgængelig.',
		'template_titledefault' => 'Standard skabelon',
		'template_descriptiondefault' => 'Standard skabelon, defineret af websitets designer.',
		'newce_defaulttext_text' => 'Indtast venligst noget tekst',
		'view_basic' => 'Basis struktur',
		'view_tree' => 'Træ struktur',
		'view_fancy' => 'Speciel struktur',
		'ruleapplies' => 'Regel gælder',
		'rulefails' => 'Overholder ikke reglerne',
		'createnewrecord' => 'Opret nyt element',
		'editrecord' => 'Rediger element',
		'pasterecord' => 'Indsæt element',
		'copyrecord' => 'Kopier element',
		'cutrecord' => 'Klip element',
		'createreference' => 'Opret reference',
		'unlinkRecord' => 'Fjern reference',
		'deleteRecord' => 'Slet element(!)',
		'deleteRecordMsg' => 'Vil du virkelig slette dette element?',
		'makeLocal' => 'Opret lokal kopi',
		'makeLocalMsg' => 'Ønsker du at oprette en lokal kopi af dette refererede element?',
		'path' => 'Sti',
	),
	'de' => Array (
		'title' => "WEB > SEITEN MODUL",
		'default_introduction' => 'Wenn Sie den Inhalt einer Seite bearbeiten möchten, klicken Sie bitte auf im Seitenbaum auf der linken Seite auf einen Seitentitel.',
		'createnewpage_title' => 'Neue Seite anlegen',
		'createnewpage_introduction' => '',
		'createnewpage_hide_header' => 'Verstecken',
		'createnewpage_hide_description' => 'Seite vor der Öffentlichkeit verstecken,',
		'createnewpage_pagetitle_header' => 'Seitentitel',
		'createnewpage_pagetitle_description' => 'Es ist erforderlich, einen Seitentitel einzugeben. Er hilft Ihnen später, Ihre Seite leicht wiederzufinden.',
		'createnewpage_templateobject_header' => 'Layout',
		'createnewpage_templateobject_description' => 'Um eine neue Seite zu erstellen, klicken Sie auf eines der folgenden Layouts oder klicken Sie auf die "Standard Layout" Schaltfläche.',
		'createnewpage_defaultlayoutsubmitlabel' => 'Neue Seite mit Standard Layout erstellen',
		'createnewpage_templateobject_createemptypage' => 'Eine leere Seite basierend auf folgendem Layout erstellen:',
		'createnewpage_templateobject_createpagewithdefaultcontent' => 'Eine Seite mit vorausgefülltem Inhalt, basierend auf folgender Vorlage erstellen:',
		'createnewcontent_newContentElement' => 'Neues Inhaltselement',
		'template_nodescriptionavailable' => 'Keine Beschreibung verfügbar.',
		'template_titledefault' => 'Standard Vorlage',
		'template_descriptiondefault' => 'Standard Layout, definiert durch den Designer dieser Website.',
		'newce_defaulttext_text' => 'Bitte geben Sie hier Text ein',
		'view_basic' => 'Standard Ansicht',
		'view_tree' => 'Baumstruktur',
		'view_fancy' => 'Spezielle Ansicht',
		'ruleapplies' => 'Regel trifft zu',
		'rulefails' => 'Regel wurde nicht erfüllt',
		'createnewrecord' => 'Neuen Datensatz anlegen',
		'editrecord' => 'Datensatz bearbeiten',
		'pasterecord' => 'Datensatz einfügen',
		'copyrecord' => 'Datensatz kopieren',
		'cutrecord' => 'Datensatz ausschneiden',
		'createreference' => 'Erstelle Verknüpfung',
		'unlinkRecord' => 'Verknüpfung entfernen',
		'deleteRecord' => 'Datensatz löschen (!)',
		'deleteRecordMsg' => 'Möchten Sie diesen Datensatz wirklich löschen?',
		'hideheaderinformation' => 'Seitenbezogene Informationen verstecken',
		'showheaderinformation' => 'Seitenbezogene Informationen anzeigen',
		'makeLocal' => 'Lokale Kopie erstellen',
		'makeLocalMsg' => 'Möchten Sie eine lokale Kopie dieses verknüpften Elements erstellen?',
		'path' => 'Pfad',
	),
);
?>
