services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tvp\TemplaVoilaPlus\:
    resource: '../Classes/*'

  Tvp\TemplaVoilaPlus\Configuration\FlexForm\ParsingModifyEventListener:
    tags:
        - name: event.listener
          identifier: 'templavoilaplus/handleFlexformIdentifier'
          method: 'setDataStructure'
          event: TYPO3\CMS\Core\Configuration\Event\BeforeFlexFormDataStructureParsedEvent

  Tvp\TemplaVoilaPlus\Form\RegisterFormEngine:
    tags:
        - name: event.listener
          identifier: 'templavoilaplus/bootComplete/registerFormEngine'
          method: 'processEvent'
          event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent

  Tvp\TemplaVoilaPlus\Configuration\ContentElementWizardItems:
    tags:
        - name: event.listener
          identifier: 'templavoilaplus/newContentElementWizardItems/modify'
          method: 'processEvent'
          event: TYPO3\CMS\Backend\Controller\Event\ModifyNewContentElementWizardItemsEvent

  Tvp\TemplaVoilaPlus\Controller\Backend\Ajax\ContentElementWizard:
    tags: [ 'backend.controller' ]

  Tvp\TemplaVoilaPlus\Controller\Backend\Ajax\ExtendedNewContentElementController:
    tags: [ 'backend.controller' ]
